# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
