# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='preventa',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
