# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preventas', '0002_auto_20160408_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
    ]
