# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-06 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_detalle_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='nota',
        ),
        migrations.AddField(
            model_name='compra',
            name='documentado',
            field=models.BooleanField(default=False),
        ),
    ]
