# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20151121_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_mayorista',
            field=models.BooleanField(default=False),
        ),
    ]
