# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20160302_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='descripcion',
            field=models.CharField(default='Detalle del precio', max_length=100),
        ),
    ]
