# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20160302_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacen',
            old_name='Producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Precio',
            new_name='precio',
        ),
    ]
