# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20160327_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Almacen',
        ),
    ]
