# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-06 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Compra'),
        ),
    ]
